import axios from 'axios';
import fs from 'fs';
import path from 'path';

interface GeminiAnalysisRequest {
  articles: Array<{
    id: string;
    title: string;
    fullBodyText: string;
    newsOutlet?: string;
    authors?: string[];
  }>;
}

interface GeminiAnalysisResponse {
  articles: Array<{
    id: string;
    summary: string;
    category: string;
    sentiment: 'positive' | 'neutral' | 'negative';
    translated: boolean;
    quotes: Array<{
      stakeholderName: string;
      stakeholderAffiliation: string;
      quote: string;
    }>;
  }>;
}

/**
 * Load prompt templates from files
 */
const loadPromptTemplate = (filename: string): string => {
  try {
    const promptPath = path.join(__dirname, '..', '..', 'docs', 'prompts', filename);
    return fs.readFileSync(promptPath, 'utf-8');
  } catch (error) {
    console.error(`Failed to load prompt template ${filename}:`, error);
    throw new Error(`Failed to load prompt template: ${filename}`);
  }
};

/**
 * Load category definitions
 */
const loadCategoryDefinitions = (): any[] => {
  try {
    const categoryPath = path.join(__dirname, '..', '..', 'docs', 'prompts', 'category-definitions.md');
    const content = fs.readFileSync(categoryPath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error('Failed to load category definitions:', error);
    return [];
  }
};

/**
 * Analyze articles using Gemini API with article analysis prompt
 * @param articles Array of articles to analyze (max 10)
 * @returns Analysis results with summaries, categories, sentiment
 */
export const analyzeArticles = async (articles: GeminiAnalysisRequest['articles']): Promise<any> => {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is required');
  }

  if (articles.length > 10) {
    throw new Error('Maximum 10 articles can be analyzed per request');
  }

  if (articles.length === 0) {
    throw new Error('At least one article is required for analysis');
  }

  // Load the article analysis prompt
  const systemPrompt = loadPromptTemplate('article-analysis.md');
  
  // Load category definitions
  const categories = loadCategoryDefinitions();
  
  // Create number range for output
  const numberRange = `1-${articles.length}`;

  const userPrompt = `Please analyze these articles:

Articles JSON:
${JSON.stringify(articles.map(article => ({
  id: article.id,
  title: article.title,
  source: article.newsOutlet || 'Unknown',
  author: article.authors?.join(', ') || '',
  date: new Date().toISOString().split('T')[0], // Current date as placeholder
  url: '', // Not available in our data
  text: article.fullBodyText
})), null, 2)}

Categories JSON:
${JSON.stringify(categories, null, 2)}

Number Range: ${numberRange}

Return the analysis in the specified JSON format.`;

  try {
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        contents: [
          {
            parts: [
              {
                text: `${systemPrompt}\n\n${userPrompt}`
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.1,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 8192,
        }
      },
      {
        headers: {
          'Content-Type': 'application/json',
        },
        timeout: 120000 // 2 minute timeout for Gemini analysis
      }
    );

    const generatedText = response.data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error('No content generated by Gemini');
    }

    // Parse the JSON response - handle markdown code blocks
    let jsonText = generatedText;
    
    // Remove markdown code blocks if present
    if (jsonText.includes('```json')) {
      const jsonMatch = jsonText.match(/```json\s*([\s\S]*?)\s*```/);
      if (jsonMatch) {
        jsonText = jsonMatch[1];
      }
    } else if (jsonText.includes('```')) {
      const jsonMatch = jsonText.match(/```\s*([\s\S]*?)\s*```/);
      if (jsonMatch) {
        jsonText = jsonMatch[1];
      }
    }
    
    // Clean up any remaining markdown artifacts
    jsonText = jsonText.trim();
    
    const analysisResult = JSON.parse(jsonText);
    
    // Validate the response structure
    if (!analysisResult.articles || !Array.isArray(analysisResult.articles)) {
      throw new Error('Invalid response format from Gemini');
    }

    return analysisResult;
  } catch (error: any) {
    if (axios.isAxiosError(error)) {
      throw new Error(`Gemini API request failed: ${error.response?.data?.error?.message || error.message}`);
    }
    if (error instanceof SyntaxError) {
      throw new Error(`Failed to parse Gemini response as JSON: ${error.message}`);
    }
    throw error;
  }
};

/**
 * Extract quotes from articles using Gemini API with quote analysis prompt
 * @param articles Array of articles to analyze (max 10)
 * @returns Quote extraction results
 */
export const extractQuotes = async (articles: GeminiAnalysisRequest['articles']): Promise<any> => {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is required');
  }

  if (articles.length > 10) {
    throw new Error('Maximum 10 articles can be analyzed per request');
  }

  if (articles.length === 0) {
    throw new Error('At least one article is required for analysis');
  }

  // Load the quote analysis prompt
  const systemPrompt = loadPromptTemplate('quote-analysis.md');
  
  // Create number range for output
  const numberRange = `1-${articles.length}`;

  const userPrompt = `Please extract quotes from these articles:

Articles JSON:
${JSON.stringify(articles.map(article => ({
  id: article.id,
  title: article.title,
  source: article.newsOutlet || 'Unknown',
  author: article.authors?.join(', ') || '',
  date: new Date().toISOString().split('T')[0], // Current date as placeholder
  text: article.fullBodyText
})), null, 2)}

Number Range: ${numberRange}

Return the quote extraction in the specified JSON format.`;

  try {
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        contents: [
          {
            parts: [
              {
                text: `${systemPrompt}\n\n${userPrompt}`
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.1,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 8192,
        }
      },
      {
        headers: {
          'Content-Type': 'application/json',
        },
        timeout: 120000 // 2 minute timeout for Gemini analysis
      }
    );

    const generatedText = response.data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error('No content generated by Gemini');
    }

    // Parse the JSON response - handle markdown code blocks
    let jsonText = generatedText;
    
    // Remove markdown code blocks if present
    if (jsonText.includes('```json')) {
      const jsonMatch = jsonText.match(/```json\s*([\s\S]*?)\s*```/);
      if (jsonMatch) {
        jsonText = jsonMatch[1];
      }
    } else if (jsonText.includes('```')) {
      const jsonMatch = jsonText.match(/```\s*([\s\S]*?)\s*```/);
      if (jsonMatch) {
        jsonText = jsonMatch[1];
      }
    }
    
    // Clean up any remaining markdown artifacts
    jsonText = jsonText.trim();
    
    const analysisResult = JSON.parse(jsonText);
    
    // Validate the response structure
    if (!analysisResult.quotes || !Array.isArray(analysisResult.quotes)) {
      throw new Error('Invalid response format from Gemini');
    }

    return analysisResult;
  } catch (error: any) {
    if (axios.isAxiosError(error)) {
      throw new Error(`Gemini API request failed: ${error.response?.data?.error?.message || error.message}`);
    }
    if (error instanceof SyntaxError) {
      throw new Error(`Failed to parse Gemini response as JSON: ${error.message}`);
    }
    throw error;
  }
};

/**
 * Test Gemini API connection
 * @returns True if connection is successful
 */
export const testGeminiConnection = async (): Promise<boolean> => {
  try {
    await analyzeArticles([{
      id: 'test',
      title: 'Test Article',
      fullBodyText: 'This is a test article for connection testing.',
      newsOutlet: 'Test Source'
    }]);
    return true;
  } catch (error: any) {
    return false;
  }
};
